module.exports = {
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.js', '**/?(*.)+(spec|test).js'],
  collectCoverageFrom: [
    'src/**/*.js',
    '!src/server.js',
    '!src/database/index.js',
    '!src/__tests__/**',
    '!src/config/**',
    '!**/node_modules/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/setup.js'],
  testTimeout: 30000,
  verbose: true,
  clearMocks: true,
  restoreMocks: true,
  resetMocks: true,
  testPathIgnorePatterns: [
    '/node_modules/', 
    '/coverage/',
    '/AppData/',
    '/.cursor/',
    '/.vscode/',
    '/cursor/',
    '/Microsoft VS Code/',
    '/Programs/',
    '/Local/',
    '/Roaming/'
  ],
  coveragePathIgnorePatterns: ['/node_modules/', '/coverage/', '/__tests__/'],
  moduleNameMapping: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  testSequencer: '@jest/test-sequencer',
  maxWorkers: '50%',
  bail: false,
  forceExit: true,
  detectOpenHandles: true,
  detectLeaks: true,
};